### ISSUE TITLE
请问什么时候才能适配5.6.9？

### ISSUE THREAD

**Issue by Adoream** [82Flex/WEIPDCRM#37]
RT

**Comment by Hintay** [comment]
Won't fix.

**Comment by andrewwiik** [comment]
What's not compatible?

**Comment by Hintay** [comment]
DCRM 1.x are not compatible with PHP 5.6+ and won't fix it.

**Comment by Adoream** [comment]
But when I install lnmp, install PHP5.6.9

**Comment by andrewwiik** [comment]
I'm offering to fix it if you tell me what is broken, It'll be a added feature to 2.0, http://imgur.com/a/gize9#6

**Comment by Hintay** [comment]
No, WEIPDCRM 2.0 base on Yii Framework, that is rebuild version.

**Comment by andrewwiik** [comment]
Do you have some sort of communication where we chat?

**Comment by Adoream** [comment]
What time is WEIPDCRM 2?

**Comment by andrewwiik** [comment]
about a week out from now if their are no hiccups

**Comment by Hintay** [comment]
If you ask the WEIPDCRM 2.0 base on Yii Framework, that need more time.
But if you ask the next version for WEIPDCRM, just wait a week.
@andrewwiik have design new UI for next version.

**Comment by Adoream** [comment]
I would expect WEIPDCRM 2.0！！

**Comment by andrewwiik** [comment]
@Hintay can you please give me what you have your version for WEIPDCRM 2.0 because a lot of my WEIPDCRM 2.0 uses Ajax now as the amount pages you had to navigate to to do simple actions was crazy, also I added some things to the users table to support profile picture and the users name, also you cant use "icons" as a folder name in the root because apache uses this it's default icons directory, I changed this to "icon" instead and just changed all references to it in the files

**Comment by Hintay** [comment]
@andrewwiik Please ask i_82 for WEIPDCRM 2.0, he have working on 2.0 base on Yii Framework.

**Comment by andrewwiik** [comment]
Okay, since I will have to completely rewrite everything for the new version now

**Comment by Lessica** [comment]
Do whatever you want to do.

**Comment by andrewwiik** [comment]
Can we all chat in some sort of room? @Lessica @Hintay

**Comment by Lessica** [comment]
QQ - International Version? Hah...

**Comment by Hintay** [comment]
i_82 have gave me the WEIPDCRM 2.0 Preview version in 2014, but he is busy working now. Maybe we should postpone the version number.

You can try this: http://imqq.com/, Chinese people generally use QQ to communicate.
